// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkplaceManagement.Domain.Context;

namespace WorkplaceManagement.Domain.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220113121910_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasCheckConstraint("CK_Employee_FirstName", "FirstName != ''");

                    b.HasCheckConstraint("CK_Employee_LastName", "LastName != ''");

                    b.HasCheckConstraint("CK_Employee_Email", "Email != '' and Email like '%@%'");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Floor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("SiteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("Name", "SiteId")
                        .IsUnique();

                    b.ToTable("Floor");

                    b.HasCheckConstraint("CK_Floor_Name", "Name != ''");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkplaceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Reservation");

                    b.HasCheckConstraint("CK_Reservation_StartTimestamp", "StartTimestamp >= SYSDATETIME()");

                    b.HasCheckConstraint("CK_Reservation_EndTimestamp", "StartTimestamp < EndTimestamp");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Site", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Site");

                    b.HasCheckConstraint("CK_Site_Name", "Name != ''");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Workplace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("FloorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("Name", "FloorId")
                        .IsUnique();

                    b.ToTable("Workplace");

                    b.HasCheckConstraint("CK_Workplace_Name", "Name != ''");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Floor", b =>
                {
                    b.HasOne("WorkplaceManagement.Domain.Model.Site", "Site")
                        .WithMany("Floors")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Reservation", b =>
                {
                    b.HasOne("WorkplaceManagement.Domain.Model.Employee", "Employee")
                        .WithMany("Reservations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkplaceManagement.Domain.Model.Workplace", "Workplace")
                        .WithMany("Reservations")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Workplace", b =>
                {
                    b.HasOne("WorkplaceManagement.Domain.Model.Floor", "Floor")
                        .WithMany("Workplaces")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Employee", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Floor", b =>
                {
                    b.Navigation("Workplaces");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Site", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("WorkplaceManagement.Domain.Model.Workplace", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
